### ISSUE TITLE
Deprecated selector in `nms-color-bracket\styles\nms-color-bracket.less`

### ISSUE THREAD

**Issue by miguerutb** [nmscholl/nms-color-bracket#1]
In `nms-color-bracket\styles\nms-color-bracket.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .colorAlert > .region` => `atom-text-editor.editor .colorAlert > .region`

* `atom-text-editor::shadow .color0 > .region` => `atom-text-editor.editor .color0 > .region`

* `atom-text-editor::shadow .color1 > .region` => `atom-text-editor.editor .color1 > .region`

* `atom-text-editor::shadow .color2 > .region` => `atom-text-editor.editor .color2 > .region`

* `atom-text-editor::shadow .color3 > .region` => `atom-text-editor.editor .color3 > .region`

* `atom-text-editor::shadow .color4 > .region` => `atom-text-editor.editor .color4 > .region`

* `atom-text-editor::shadow .color5 > .region` => `atom-text-editor.editor .color5 > .region`

* `atom-text-editor::shadow .color6 > .region` => `atom-text-editor.editor .color6 > .region`

* `atom-text-editor::shadow .color7 > .region` => `atom-text-editor.editor .color7 > .region`

* `atom-text-editor::shadow .color8 > .region` => `atom-text-editor.editor .color8 > .region`

* `atom-text-editor::shadow .color9 > .region` => `atom-text-editor.editor .color9 > .region`

* `atom-text-editor::shadow .color10 > .region` => `atom-text-editor.editor .color10 > .region`

* `atom-text-editor::shadow .color11 > .region` => `atom-text-editor.editor .color11 > .region`

* `atom-text-editor::shadow .color12 > .region` => `atom-text-editor.editor .color12 > .region`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by linjialiang** [comment]
me too

**Comment by Gaeta** [comment]
Its happening again
